name: adrop
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  rust_lib_adrop:
    path: rust_builder
  flutter_rust_bridge: 2.1.0
  url_launcher: ^6.3.0
  flutter_inappwebview: ^6.0.0
  flutter_styled_toast: ^2.2.1
  desktop_drop: ^0.4.4
  cross_file: ^0.3.4+2
  file_picker: ^8.0.6
  window_manager: ^0.3.9
  tray_manager: ^0.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - lib/assets/
