// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.1.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'data_obj/enums.dart';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class Device {
  final String name;
  final String folderFileId;
  final int deviceType;

  const Device({
    required this.name,
    required this.folderFileId,
    required this.deviceType,
  });

  @override
  int get hashCode =>
      name.hashCode ^ folderFileId.hashCode ^ deviceType.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Device &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          folderFileId == other.folderFileId &&
          deviceType == other.deviceType;
}

class LoginInfo {
  final LoginState state;

  const LoginInfo({
    required this.state,
  });

  @override
  int get hashCode => state.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LoginInfo &&
          runtimeType == other.runtimeType &&
          state == other.state;
}

class SpaceInfo {
  final String driveId;
  final String devicesRootFolderFileId;
  final String thisDeviceFolderFileId;
  final String truePassBase64;

  const SpaceInfo({
    required this.driveId,
    required this.devicesRootFolderFileId,
    required this.thisDeviceFolderFileId,
    required this.truePassBase64,
  });

  @override
  int get hashCode =>
      driveId.hashCode ^
      devicesRootFolderFileId.hashCode ^
      thisDeviceFolderFileId.hashCode ^
      truePassBase64.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SpaceInfo &&
          runtimeType == other.runtimeType &&
          driveId == other.driveId &&
          devicesRootFolderFileId == other.devicesRootFolderFileId &&
          thisDeviceFolderFileId == other.thisDeviceFolderFileId &&
          truePassBase64 == other.truePassBase64;
}
