// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.1.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../data_obj.dart';
import '../data_obj/enums.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are not used by any `pub` functions: `SENDING_TASKS`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `deref`, `initialize`

Future<List<SendingTask>> listSendingTasks() =>
    RustLib.instance.api.crateApiSendingListSendingTasks();

Future<void> addSendingTasks({required List<SendingTask> tasks}) =>
    RustLib.instance.api.crateApiSendingAddSendingTasks(tasks: tasks);
