// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.4.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<void> openByBrowser({required String url}) =>
    RustLib.instance.api.crateApiSystemOpenByBrowser(url: url);

Future<void> openFile({required String path}) =>
    RustLib.instance.api.crateApiSystemOpenFile(path: path);

Future<void> showFileInExplorer({required String path}) =>
    RustLib.instance.api.crateApiSystemShowFileInExplorer(path: path);
