// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.1.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../data_obj.dart';
import '../data_obj/enums.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `clear`, `set`, `unset`

Future<LoginInfo> loginInfo() => RustLib.instance.api.crateApiUserLoginInfo();
