// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.4.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `api`, `index`, `map_err`, `oauth_authorize_body_inner`, `oauth_authorize_body`, `oauth_authorize`, `run_warp_server`, `url_by_app_config_body`, `url_by_app_config_inner`, `url_by_app_config`
// These types are ignored because they are not used by any `pub` functions: `SHUTDOWN`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `deref`, `initialize`

Future<void> startLoginService() =>
    RustLib.instance.api.crateApiUserSettingStartLoginService();

Future<void> stopLoginService() =>
    RustLib.instance.api.crateApiUserSettingStopLoginService();
